### PR TITLE
add gulp command on package.json

### PR DESCRIPTION
**Pull request by hideokamoto**
- Add build command into package.json
- Use `Gulp` command in `node_modules/`

### CODE REVIEW

**Comment by emaildano** [comment]
@hideokamoto These already exist in the `gulpfile.js`. Are you sure adding them to the package.json is necessary?

https://github.com/megumiteam/dc-pattern-lib/blob/master/gulpfile.js#L315
https://github.com/megumiteam/dc-pattern-lib/blob/master/gulpfile.js#L38

```
$ gulp serve
[17:48:30] Using gulpfile ~/Dev/dc-pattern-lib/gulpfile.js
[17:48:30] Starting 'watch_bundle'...
[17:48:30] Finished 'watch_bundle' after 86 ms
[17:48:30] Starting 'serve'...
[17:48:34] Finished 'serve' after 3.96 s
[BS] Access URLs:
 ----------------------------------
       Local: http://localhost:3000
    External: http://10.0.1.44:3000
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.1.44:3001
 ----------------------------------
[BS] Serving files from: ./
```

```
$ danielolson : ~/dev/dc-pattern-lib [master]
$ gulp --production
[17:51:22] Using gulpfile ~/Dev/dc-pattern-lib/gulpfile.js
[17:51:22] Starting 'default'...
[17:51:22] Starting 'clean'...
```

**Comment by hideokamoto** [comment]
I wanna use gulp command as locally.
If use `gulp` command, people should install gulp as globally by themselves.
But use `./node_modules/gulp/bin/gulp.js`, we should do only run `npm install`.
It is very simple way to initiate our development.

**Comment by emaildano** [comment]
@hideokamoto I understand. If it is just a controller for Gulp I'm fine with that.

**Comment by emaildano** [comment]
@hideokamoto With that change please also update the README.md.

**Pull request merged**
